FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

ENV TZ=Europe/Copenhagen
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# install essentials
RUN apt-get update && apt-get install -y \
		ssh \
		sudo \
		wget \
		nano \
		git \
		ffmpeg \
		htop \
		gnuplot \
		build-essential \
		mpich \
		software-properties-common ;\
		rm -rf /var/lib/apt/lists/*

# add user "foam"
RUN useradd --user-group --create-home --shell /bin/bash foam ;\
	echo "foam ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    

ENV HDF5_MAJOR_REL       hdf5-1.12
ENV HDF5_MINOR_REL       hdf5-1.12.0
ENV HDF5_SRC_URL   http://support.hdfgroup.org/ftp/HDF5/releases
RUN cd /tmp                                                                        ; \
    echo "Getting: ${HDF5_SRC_URL}/${HDF5_MAJOR_REL}/${HDF5_MINOR_REL}/src/${HDF5_MINOR_REL}.tar"                ; \
    wget ${HDF5_SRC_URL}/${HDF5_MAJOR_REL}/${HDF5_MINOR_REL}/src/${HDF5_MINOR_REL}.tar                           ; \
    tar -xvf ${HDF5_MINOR_REL}.tar --directory /usr/local/src                      ; \
    rm ${HDF5_MINOR_REL}.tar                                                       ; \
    cd /usr/local/src/${HDF5_MINOR_REL}                                            ; \
    ./configure --enable-parallel --enable-shared --prefix=/usr/local/hdf5-install/                                           ; \
    make                                                                           ; \
#    make check                                                                     ; \
    make install                                                                   ; \
#    make check-install

# download athena++ from git
RUN cd /mnt                                                                        ; \
    git clone --branch Moran https://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@github.com/MoranEzra/Athena-RFX-KL2.git

